name: CI_CD

on: [push, pull_request]

jobs:
  FrontEnd-build:
    runs-on: ubuntu-latest
    env:
      CI: true
      working-directory: front-end
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: front-end
        run: npm ci
      - name: Lint
        working-directory: front-end
        run: npm run lint
      - name: Load FIREBASE Config
        working-directory: front-end
        run: |
          echo 'FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}' >> config/.env.production
          echo 'FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}' >> config/.env.production
          echo 'FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}' >> config/.env.production
          echo 'FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}' >> config/.env.production
          echo 'FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}' >> config/.env.production
          echo 'FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}' >> config/.env.production
          echo 'FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}' >> config/.env.production
      - name: Unit Test
        working-directory: front-end
        run: npm run coverage
        env:
          HEADLESS: true
      - name: E2E Test
        working-directory: front-end
        if: github.ref == 'refs/heads/master'
        run: start-server-and-test start http://localhost:8080 test:e2e
        env:
          HEADLESS: true
      - name: Build
        working-directory: front-end
        run: |
          npm run build
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: front-end/dist
